name: CI/CD to Huawei SWR and CCE

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl v1.23
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
        
      # - name: Checkout code
      #   uses: actions/checkout@v3
        
      - name: get CCE Cluster Credentials
        uses: huaweicloud/cce-credential-action@v1.0.1
        with:
          ak: ${{ secrets.ACCESSKEY }}
          sk: ${{ secrets.SECRETACCESSKEY }}
          region: "af-south-1"
          project_id: "xxxxxxx"
          cluster_id: "xxxxxx"
          
      - name: get CCE Cluster info
        run: |
          kubectl version --short
          kubectl config view
          kubectl cluster-info
          kubectl get pod,svc --all-namespaces
