name: CI/CD to Huawei SWR and CCE

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:        
      # - name: Checkout code
      #   uses: actions/checkout@v3
        
      - name: get CCE Cluster Credentials
        uses: JimohHWC/cce-credential-action@v1.0.0
        with:
          ak: ${{ secrets.ACCESSKEY }}
          sk: ${{ secrets.SECRETACCESSKEY }}
          region: "af-south-1"
          project_id: "eecc7ec81ad346adbcde0a07fa343cb0"
          cluster_id: "8817579e-f98a-11ee-990c-0255ac1000eb"
          
      - name: get CCE Cluster info
        run: |
          kubectl version --short
          kubectl config view
          kubectl cluster-info
          kubectl get pod,svc --all-namespaces
